@startsalt
{
  {/ <b>Відділення | [ Створити посилку ] }
  --
  {+
    <b>вул. Академіка Янгеля, 20
    Зайнято: 1/3
    [ Деталі ]
  }
  {+
    <b>вул. Борщагівська, 144
    Зайнято: 3/3 (ЛІМІТ)
    [ Деталі ]
  }
}
@endsalt