 @startsalt
 {
   [ <- Назад ]
   --
   <b>вул. Борщагівська, 144
   --
   {+
     <b>Зайнятість відділення
     === 3 / 3 ===
     [!] Увага: Немає вільних місць
   }
   --
   <b>Посилки на відділенні (ready_for_pickup)
   * UUID: 123e4567... | Отримувач: Іванов І.
   * UUID: 987fcdeb... | Отримувач: Петров П.
   * UUID: 556adcf1... | Отримувач: Сидоров С.
 }
 @endsalt