@startsalt
{
  <b>Нове відправлення
  --
  Відділення призначення *
  ^Оберіть відділення зі списку...^
  Вага (кг) *
  "Наприклад: 1.5           "
  Оголошена вартість (ГРН) *
  "0.00                     "
  ПІБ отримувача *
  "Іванов Іван Іванович     "
  Телефон отримувача *
  "+380XXXXXXXXX            "
  Email отримувача
  "example@domain.com       "
  --
  [ Створити ]
}
@endsalt