@startsalt
{
  <b>Нове відправлення
  --
  {+
    <b>[!] Знайдено 2 помилки:
    1. Вага має бути більше нуля.
    2. Введіть коректний email.
  }
  --
  Вага (кг) *
  "-1.0                     "
  <i><color:red>Помилка: Вага має бути більше нуля.</color>
  
  Email отримувача
  "bad-email.com            "
  <i><color:red>Помилка: Введіть коректний email.</color>
  --
  [ Створити ]
}
@endsalt