@startsalt
{
  {+
    <b>[v] Відправлення успішно зареєстровано
  }
  --
  <b>Посилка: 123e4567-e89b-12d3...
  --
  <b>Статус: </b> processing
  <b>Відділення: </b> вул. Академіка Янгеля, 20
  <b>Вага: </b> 1.5 кг
  <b>Вартість: </b> 500.00 грн
  <b>Отримувач: </b> Іванов Іван Іванович
  <b>Телефон: </b> +380671234567
  --
  {/ [ Видати клієнту ] | [ Скасувати відправлення ] }
}
@endsalt