@startsalt
{
  <b>Стан: Порожньо (Empty)
  {+
    Немає даних для відображення
    [ Оновити ]
  }
  --
  <b>Стан: Помилка сервера (404/500)
  {+

    Щось пішло не так або запис не знайдено
    [ На головну ]
  }
}
@endsalt